matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: "10"
    env:
      - ELECTRON_CACHE=$HOME/.cache/electron
      - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic

branches:
  except:
  - code-analysis

cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env GH_TOKEN="${GH_TOKEN}" \
        --env TRAVIS_BRANCH="${TRAVIS_BRANCH}" \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn dist-lw"
    else
      yarn && yarn dist
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine